### ISSUE TITLE
Any plans to make fiirst release?

### ISSUE THREAD

**Issue by kloczek** [libcamera-org/libcamera#1]
Just asking ..  :)

**Comment by kbingham** [comment]
We have release 0.0.0 ... and every commit after that currently provides a new point-release ;-)

We don't intend to declare a stable API/ABI until we have a few more core framework issues resolved which we know will break ABI/API - so there's no point us trying to declare now that we won't change it (which is what 'declaring a release' is).

Do you need a specific release point for something in particular?
Our utils/gen-version.sh script generates a linear tag for every commit, as we 'release' it.

This should be sufficient to determine which version you are currently using, and when we declare a stable API/ABI we will increment one of the semver type variables and tag accordingly.

**Comment by kloczek** [comment]
To be able include libcamera in my distro it would be good to have kind of API/ABI stability :)
I understand that on current stage stabilising API/ABI and make first release may take a bit longer. That is not any problem ..

Do you have any estimation (even quite murky) how long current stage may take? :P
Question is only in context my own other tasks coordination ..

Versioning is only matter of packaging. So even if it is kind of early-development-stage IMO it would be good to male some 0.x[.x] release just to give other people kind of impulse to integrate some API changes :)
As long as libcamera would be able to provide API description in form of pkgconfig file other projects may start require exact minimum version of the libcamera on build stage.
Even after that still bigger or smaller changes in API/ABI me not be held by anything :)

Thank you for reply :)

**Comment by kbingham** [comment]
What is your distribution?
We tagged our initial commit recently as 0.0.0 specifically for this purpose to support early packaging in distributions, which I believe RedHat at least use.

It would be no different if that initial commit was 0.0.1, or 0.0.0. The version increments on every commit after that, as can be seen in utils/gen-version.sh and in the output of the debug utilities with lines such as:

libcamera v0.0.0+3403-d41b0337

So it is version 0.0.0 with a point release of 3403, and built against the exact commit d41b0337

Looking at the generated libcamera.pc it looks like it sets a version of: Version 1.0
That's incorrect really, if you can find a way to get that generated correctly from meson, we can integrate a patch.

**Comment by kloczek** [comment]
Any progress on make acrual 1.0 release and tag it? 🤔

**Comment by kbingham** [comment]
No, that requires us to get to the stage where we can say we won't change the ABI which we are not yet willing to commit to.

You are welcome to consider any update to the master branch the latest release. It's version is defined as v0.0.0-(number of commits). This information is displayed when the library starts up, and can be accessed at runtime by checking the CameraManager::version() method.

For example, I currently have:

[27:58:18.487945736] [690121]  INFO Camera camera_manager.cpp:293 libcamera v0.0.0+3423-807b9484

No ABI or API stability is guaranteed right now, and we have plans to actively change some of the APIs. That doesn't mean it's going to change drastically or rapidly, or even necessarily in the near future, but it means I'm not able to guarantee that it won't change before we tag a 1.0.

If you develop an application which uses libcamera, and would like to include your build in our tests we can add them to our builders, and/or alert you if any ABI/API breakage causes compilation to fail.

**Comment by kloczek** [comment]
gentle ping 😋 
Still no stable ABI/API? 🤔

**Comment by kbingham** [comment]
What are your requirements for a release? or a release tag?
What do you need to include in your package?

**Comment by kloczek** [comment]
I need a version .. only this and nothing more.
https://github.com/libcamera-org/libcamera/tags still is empty.
I may I ask tag that verion using `<version.with.dots>` string.

**Comment by kbingham** [comment]
You can generate this yourself already.

From the source tree,
  ./utils/gen-version.sh

**Comment by kloczek** [comment]
I can do many things but I cannot decide about make the first official release of that project 😋

**Comment by kbingham** [comment]
Every commit has a unique version string. You can always pick the latest which you wish to package.

libcamera-clean$ ./utils/gen-version.sh 
0.0.0+3600-e115a691

That's the current version.

**Comment by kbingham** [comment]
You are welcome to package that as a release for your OwnOS. You could use automated  tooling to update every time we push an update.

Are you using libcamera? or just packaging it?

**Comment by kloczek** [comment]
Moment .. so you are not going to make first release .. ever? 🤔 

Usimg git hash in version does not guarantee that next version will be bigger
Usimg `+` and `-` is not allowed to use in version string in case of rpm and Solaris IPS (*BSD packaging tooling IIRC as does not allow for that).

In caseof breaking ABI/ABI you can always increase SONAME. In case of adding some new symbols DSOs allowy use versioned SONAMes. With that you can change API or ABI at any time.
What is the actual current problem with make first release? 🤔

**Comment by kbingham** [comment]
>  What is the actual current problem with make first release? 

Convincing the team lead to allow it before we declare a stable ABI.
Of which we know we still have a lot of work to do, to get to that point.

And from when we make a first release, when should we make another one? How often? Should we have extra workload to maintain branches from old releases with bugfixes ? What is the release strategy? What point declares a release? How much extra work is involved in making a release, which takes away effort that could be spent working towards all the work we already have to do?

If you have answers to those or would like to assist in becoming the project release manager to help handle it all - then we would welcome the assistance. But otherwise the default answer to 'what's the latest release' is "The latest commit on HEAD".

**Comment by kbingham** [comment]
(That's a genuine statement by the way, if you think you can help with all this, please let us know)

**Comment by kbingham** [comment]
> In caseof breaking ABI/ABI you can always increase SONAME. In case of adding some new symbols DSOs allowy use versioned SONAMes. With that you can change API or ABI at any time.

If this can be automated, I'd be all for pushing again on Laurent... I've tried using abi-compliance-checker, so I think there's some possibiltiy there, but I haven't been able to turn that into a fully automated way to detect ABI breakage to update the versions from that.

**Comment by kloczek** [comment]
> Convincing the team lead to allow it before we declare a stable ABI.
> Of which we know we still have a lot of work to do, to get to that point.

But you know that AlwaysItWillBeSomethingToDo™️  😋 
Issue ias about makeing some milestones.

**Comment by kloczek** [comment]
Still no plans to make first release? 🤔

**Comment by kbingham** [comment]
Still waiting for someone to step up and help volunteer as a release manager ... Or give me extra hours in the day 

But more seriously, yes there has been progress. Help would ... Help.. But it's in progress

**Comment by kloczek** [comment]
If may I help somehow .. just remember that software it is something which constantly evolving so releases points are only kind of conventional points. After first release more commits you will be waiting with next release than more you will be hesitating with making decision about next release. Bugs are not any problems. Only problem is how quickly those bugs re fixed and pushed as next release. This is why some maintainers decides to make next rerelease even after couple of hours to push some code snapshots as new releases.
IMO you should make first release long time ago .. but it is only my opinion .. 😋 

Cheers 😄

**Comment by kbingham** [comment]
https://git.libcamera.org/libcamera/libcamera.git/commit/?id=a83aed77df1258e469c0eb42d9cb4f1938db53f2
