### ISSUE TITLE
slots() and emit() functions conflict with Qt keywords

### ISSUE THREAD

**Issue by kbarni** [libcamera-org/libcamera#2]
`slots` and`emit` are keywords for Qt, and also functions in the `SignalBase` class (`signal.h:31`).

Thus, when trying to use libcamera in a Qt application, it will throw errors, as moc generator will try to convert them to macros.

Would it be possible to rename those functions, so it won't conflict the QT keywords?

As a workaround the QT_NO_KEYWORDS compile flag can be specified and the keywords changed to `Q_SLOTS`, `Q_EMIT` etc., but it's quite confusing.

**Comment by kbingham** [comment]
Hi @kbarni as you may have seen we just use the QT_NO_KEYWORDS when building with QT5.

This might be a discussion point you could raise on the libcamera-mailing list though.

What would you recommend renaming them to?

**Comment by kbingham** [comment]
Alternatively could you create a bug on https://bugs.libcamera.org/ so we can track this and try to resolve before we freeze the API.

**Comment by kbingham** [comment]
Closing. Any further discussions shall take place on the libcamera-devel maililng list. This unofficial mirror is likely to be closed.
