### ISSUE TITLE
Libcamera does not start when stopped

### ISSUE THREAD

**Issue by chrizbee** [libcamera-org/libcamera#3]
After stopping the camera it won't restart (`requestCompleted` is not emited).

This can be tested with the qcam toolbar actions (stop capture, start capture).

Also it does not matter which renderer is chosen (Qt, OpenGL).

**Comment by opit7** [comment]
+1

**Comment by kbingham** [comment]
Can you clarify which platform you are on ? Is this a Raspberry Pi - or a Surface Go perhaps?

**Comment by kbingham** [comment]
I've just tested an RPi with libcamera  0.0.0+3913-685da13d and stop start works. Next trying the latest master branch.

**Comment by kbingham** [comment]
@chrizbee Can you provide full logs while you do this please? Seems we can't replicate that here.

run 
`LIBCAMERA_LOG_LEVELS=:0 qcam`

Then do the start / stop / start cycle, and presumably close when it's failed.


And capture the text, and upload it on this issue.

**Comment by kbingham** [comment]
@opit7 Same request to you too please if you are hitting this. Also please state which camera you are using, and if you have self built libcamera, or if you have used packages from Raspberry Pi - or from Arducam.

**Comment by chrizbee** [comment]
Sorry for the late reply @kbingham - unfortunately I didn't receive any notifications from GitHub...

What I'm using:
- Raspberry Pi 4 2GB
- Latest Raspberry Pi OS (64bit)
- ArduCAM 64MP Autofocus Camera from [RobotShop](https://www.robotshop.com/de/en/arducam-64mp-autofocus-camera-raspberry-pi.html)
- libcamera and drivers installed like described [here](https://www.arducam.com/docs/cameras-for-raspberry-pi/64mp-camera-for-raspberry-pi/how-to-use-arducam-64mp-camera-on-rapberry-pi/#how%C2%A0to%C2%A0install%C2%A0the%C2%A0driver) (-dev and -apps are 0.0.10)

ArduCAM support has confirmed, that `qcam` start/stop is not working for them too (on RPi).

The debug output is pretty long, so I pasted it [in a pastebin](https://pastebin.com/raw/wKiqgGAi).
- Stop: [0:10:18.643070655]
- Restart: [0:10:22.388419896]
- Close: [0:10:26.230489334]

The problem I faced is, that new requests won't be delivered to the app (both for qcam and my own app) which can be seen in this part of the debug log:
```
[0:10:22.780864600] [1816] DEBUG RPI raspberrypi.cpp:1121 queueRequestDevice: New request.
[0:10:22.780905748] [1816] DEBUG RPI raspberrypi.cpp:1121 queueRequestDevice: New request.
[0:10:22.780929415] [1816] DEBUG RPI raspberrypi.cpp:1121 queueRequestDevice: New request.
[0:10:22.780952397] [1816] DEBUG RPI raspberrypi.cpp:1121 queueRequestDevice: New request.
[0:10:22.780974230] [1816] DEBUG Event event_dispatcher_poll.cpp:216 next timer 0x7f94004fa8 expires in 142.043658221
[0:10:26.230489334] [1818] DEBUG Camera camera.cpp:1232 Stopping capture
[0:10:26.243765547] [1816] DEBUG Request request.cpp:122 Request(0:X:0/1:0)
[0:10:26.243861769] [1816] DEBUG Request request.cpp:122 Request(1:X:0/1:0)
[0:10:26.243888029] [1816] DEBUG Request request.cpp:122 Request(2:X:0/1:0)
[0:10:26.243913269] [1816] DEBUG Request request.cpp:122 Request(3:X:0/1:0)
```

**Comment by kbingham** [comment]
I *hate* this answer, but I'm afraid as you are using the Arducam fork - This is a problem for Arducam to solve. They will need to rebase on top of the latest libcamera, and if the issue still persists, *then* they can contact RPi for support.

**Comment by chrizbee** [comment]
> I _hate_ this answer, but I'm afraid as you are using the Arducam fork - This is a problem for Arducam to solve. They will need to rebase on top of the latest libcamera, and if the issue still persists, _then_ they can contact RPi for support.

Fair enough. I will close this issue as soon as I find a solution to the problem so I can post it here (since the ArduCAM fork is closed source?)

**Comment by kbingham** [comment]
Yes, they chose to keep it closed, I'm trying to work with them to get it open - or for them to use 'upstream' - which at that point, we would be able to help. But we haven't got there yet. I need to get back to them on that, but ultimately, this ball is in their court.

Please feel free to mention back to Arducam support that because their camera support is not upstream we can't support you, and it is *their* responsibility to fix this.

**Comment by chrizbee** [comment]
So they confirmed that `qcam` is not working for them either.

But they sent me a link to one of their projects where stopping and restarting the stream should work.
https://github.com/ArduCAM/mjpg-streamer/blob/master/mjpg-streamer-experimental/plugins/input_libcamera/LibCamera.cpp

Still I didn't figure out a way to make it work for me (yet)...

**Comment by kbingham** [comment]
@chrizbee - Unfortunately, this could be a bug introduced by Arducam, or it could be fixed in a newer release of libcamera.

Either way, as long as Arducam keep their sources to themselves, it is their responsibility to fix this.
If you can reproduce this issue with a non-Arducam camera (the V2 IMX219 or HQ IMX477) then we could isolate a cause.

If we can't reproduce on the mainline tree, then I'm afraid that the bug is simply 'in Arducam's forked code'.

**Comment by chrizbee** [comment]
So there is a workaround for this.

I had to rename `dtoverlay=arducam_64mp` to `dtoverlay=arducam-64mp` in RPis `/boot/config.txt`.
Though it's not a typo - see quote from ArduCAM support:

> I want to explain briefly. It's not the script's fault, it might be the compiler's problem. Arducam-64mp is officially compiled by Raspberry Pi according to our source code, and arducam_64mp is compiled by the environment we built with docker. Their source code is essentially the same.It seems that the driver we compiled has some problems when using qcam. But this is just a phenomenon, not the basis of the problem, which needs to be checked.

> At present, for users who want to use qcam, I would recommend using arducam-64mp. Since we have a lot of other plans, fixing this won't be anytime soon. So if the Raspberry Pi version is available, you can use it for now.

Just posting this here fyi and if anyone else has the same problem.
