### ISSUE TITLE
Unhandled python exception This is a Meson bug and should be reported!

### ISSUE THREAD

**Issue by lm782** [libcamera-org/libcamera#5]
Total newbie here. "Simply" attempting to build/install libcamera on a Raspberry Pi 4B (8 GB) and Ubuntu 22.04 LTS (for the second time, this time taking notes…) For whatever it's worth, this is new hardware, new image…

Confirmed the HQ camera and hardware work as expected using an SD card with a Raspberry PI OS image and running libcamera-hello successfully. 

Used a new SD card to load Ubuntu 22.04 LTS, ran sudo apt update, upgrade, and rebooted. Installed G++, PIP3,  meson, libyaml-dev, python3-yaml, python3-ply, python-jinja2, libgnutls-28-dev, libdw-dev, libunwind-dev and attempted start the build when got an error to install git, which I then did. 

Ran "git clone https:…" successfully and changed directories to libcamera. Attempted to run "meson setup build" and got an error to install meson (so I ran "sudo apt install meson"). Attempting to build again gave, "Error: Unable to find CMake". 

Looking at the log file, among other things, meson-logs.txt said, 
"Running compile:
Working directory:  /home/luis/libcamera/build/meson-private/tmp4l161z6z
Command line:  cc /home/luis/libcamera/build/meson-private/tmp4l161z6z/testfile.c -o /home/luis/libcamera/build/meson-private/tmp4l161z6z/output.obj -c -D_FILE_OFFSET_BITS=64 -O0
…
Compiler stderr:
 /home/luis/libcamera/build/meson-private/tmp4l161z6z/testfile.c: In function 'main':
/home/luis/libcamera/build/meson-private/tmp4l161z6z/testfile.c:6:17: error: 'issetugid' undeclared (first use in this function); did you mean 'setegid'?
    6 |                 issetugid;
      |                 ^~~~~~~~~
      |                 setegid
/home/luis/libcamera/build/meson-private/tmp4l161z6z/testfile.c:6:17: note: each undeclared identifier is reported only once for each function it appears in
…"
--> Not sure why the compiler threw the undeclared identifier error. 

--> Further down in meson-logs.txt it looks like pkg-config was missing
"Trying a default Pkg-config fallback at pkg-config
Did not find pkg-config by name 'pkg-config'
Found Pkg-config: NO
Pkg-config binary for machine 1 not found. Giving up.
CMake binary for 1 is not cached
CMake binary missing from cross or native file, or env var undefined.
Trying a default CMake fallback at cmake
Did not find CMake 'cmake'
Found CMake: NO
CMake binary for machine 1 not found. Giving up."

Ran "sudo apt install pkg-config" and tried another "meson setup build", which seems to have completed. 

Tried running "cam -l" and got "Command 'cam' not found, but can be installed with: "sudo apt install libcamera-tools". Installed libcamera-tools. 

Realized I missed a step and ran "ninja -C build install" 
- Near the end I was prompted for a password, which I entered
- Got an error, 
"ERROR: Unhandled python exception
This is a Meson bug and should be reported!
FAILED: meson-internal__install
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.

Reran "ninja -C build install" and got, 
- "ninja: Entering directory 'build'
- [1/2] Installing files.
Installation failed due to insufficient permissions…"

Reran command with sudo, "sudo ninja -C build install" and got same error

Tried "cam -l" and got "Segmentation fault (core dumped) and an Ubuntu error.

One last time and then I plead uncle... 

"luis@Ubuntu-RPi4:~/libcamera$ sudo ninja -C build install
ninja: Entering directory `build'
[1/2] Installing files.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 811, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 564, in do_install
    d = self.check_installdata(pickle.load(ifile))
AttributeError: Can't get attribute 'OptionString' on <module 'mesonbuild.interpreter.primitives.string' from '/usr/lib/python3/dist-packages/mesonbuild/interpreter/primitives/string.py'>
ERROR: Unhandled python exception
    This is a Meson bug and should be reported!
FAILED: meson-internal__install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
luis@Ubuntu-RPi4:~/libcamera$"

I give. (Not sure why the text above is crossed out). Can anyone offer some insight on what might be going on? 
Luis

**Comment by eli-schwartz** [comment]
> ```
> AttributeError: Can't get attribute 'OptionString' on <module 'mesonbuild.interpreter.primitives.string' from '/usr/lib/python3/dist-packages/mesonbuild/interpreter/primitives/string.py'>
> ```

This looks quite odd, did you install a user copy of meson using `pip install --user` and then try to install as root?

If so, see the warning at https://mesonbuild.com/Getting-meson.html#installing-meson-with-pip

**Comment by lm782** [comment]
Thanks for the ''' clarification, help and link. I ran "pip3 install --user meson" and "pip3 install --user --upgrade meson" to install meson, just after G++ and pip3 (and before yaml, jinja2...). 

After cloning and moving to the libcamera directory, I ran "meson setup build". Thinking/Believing I had already installed it, I was surprised to get "Command 'meson' not found, but can be installed with: sudo apt install meson". 

Instead of troubleshooting a potential path problem, no mention of a potential path issue in the libcamera Getting Started page, I did what I was told - and used sudo to install meson a second time. 

Sounds like the best option is, "sudo  apt remove meson" add "~/.local/bin" and try again?

**Comment by eli-schwartz** [comment]
Well, pip itself would mention adding that to PATH. :)

> Sounds like the best option is, "sudo apt remove meson" add "~/.local/bin" and try again?

That would work... unless you wanted to run `sudo ninja -C build install` which requires you to install Meson as root.

In this case, the Meson from apt is 0.61.2 (available in Ubuntu 22.04 LTS "Jammy"), which is good enough for libcamera.

I would uninstall the one you installed with pip, then `rm -rf build/` and try again using just the apt package.

(The problem is that if you have both of them installed, python itself will locate the version installed as the current user. Then when you try to run meson as root during "install" it only finds a different version, and the internal data files are incompatible between versions of Meson.)

**Comment by lm782** [comment]
Thanks. Uninstalled Meson using pip and removed build directory (in libcamera subdirectory). Ran "sudo ninja -C build install" and got, 
"ninja: Entering directory 'build'
ninja: fatal: chdir to 'build' - No such file or directory." 

Ran "meson setup build" which gave two warnings ("Python files installed by Meson might not be found by python interpreter."), preceded by "Program python3 (jinja2, ply, jina2, yaml) found: YES (/usr/bin/python3) modules: jinja2, ply, jinja2, yaml" 
1. "This warning can be avoided by setting "python.platlibdir" option." 
2. "This warning can be avoided by setting "python.purelibdir" option." 

Searched the error and found https://mesonbuild.com/Python-module.html, which says to set the variable using "meson setup". Setting the python.platlibdir option to /usr/bin/python3, I got an error saying I must set at least one directory. Looking at the file structure /usr/bin/python3 is a link and not a directory. 

Searching local storage (SD card) was not very helpful figuring out the path to PyYAML and Jinja2 (a relatively common started with /snap/core20... which looks specific to Ubuntu). 

Feels like I might be missing something obvious, but I don't see it...

**Comment by eli-schwartz** [comment]
> Setting the python.platlibdir option to /usr/bin/python3, I got an error saying I must set at least one directory.

You set it to a file instead of a directory. :eyes:

**Comment by lm782** [comment]
Thank you. I see/saw that - it's a link and therefore a file, not a directory. Sorry I wasn't clear. 

What I don't "see" is the directory(ies) Meson ought to look in for jinja2, ply, yaml so that platlibdir and purelibdir can be set accordingly. (Not sure why "meson setup build' lists, or is looking for, jinja2 twice.)

**Comment by lm782** [comment]
The plot thickens... Using "pip show", found pyyaml, ply and jinja2 in two different directories. 
pyyampl in /usr/lib/python3/dist-packages
ply in 'home/luis/.local/lib/python3.10/site-packages, and 
jinja2 in /home/luis/.local/lib/python3.10/site-packages

Other than it likely won't find pyyaml, is there a potential problem setting python.platlibdir and python.purelibdir to look in /home/luis/.local/lib/python3.10/site-packages?

**Comment by lm782** [comment]
Ignored warning (pretended it isn't there), ran "sudo ninja -C build install" and got three failed messages: "No module named 'ninja2'", "...'ply'" , and "...ninja2". Details below. Was I supposed to run a different command? 

```
luis@Ubuntu-RPi4:~/libcamera$ sudo ninja -C build install
ninja: Entering directory `build'
[4/176] Generating include/libcamera/internal/tp_header with a custom command
FAILED: include/libcamera/internal/tracepoints.h
/home/luis/libcamera/utils/tracepoints/./gen-tp-header.py /home/luis/libcamera/build/include include/libcamera/internal/tracepoints.h ../include/libcamera/internal/tracepoints.h.in ../include/libcamera/internal/tracepoints/buffer_enums.tp ../include/libcamera/internal/tracepoints/request_enums.tp ../include/libcamera/internal/tracepoints/pipeline.tp ../include/libcamera/internal/tracepoints/request.tp
Traceback (most recent call last):
  File "/home/luis/libcamera/utils/tracepoints/./gen-tp-header.py", line 10, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
[8/176] Generating include/libcamera/ipa/core_mojom_module with a custom command
FAILED: include/libcamera/ipa/core.mojom-module
/home/luis/libcamera/utils/ipc/./parser.py --output-root /home/luis/libcamera/build --input-root /home/luis/libcamera --mojoms ../include/libcamera/ipa/core.mojom
Traceback (most recent call last):
  File "/home/luis/libcamera/utils/ipc/./parser.py", line 18, in <module>
    import mojo.public.tools.mojom.mojom_parser as parser
  File "/home/luis/libcamera/utils/ipc/mojo/public/tools/mojom/mojom_parser.py", line 26, in <module>
    from mojom.parse import parser
  File "/home/luis/libcamera/utils/ipc/./mojo/public/tools/mojom/mojom/parse/parser.py", line 12, in <module>
    from mojom.parse.lexer import Lexer
  File "/home/luis/libcamera/utils/ipc/./mojo/public/tools/mojom/mojom/parse/lexer.py", line 13, in <module>
    from ply.lex import TOKEN
ModuleNotFoundError: No module named 'ply'
[9/176] Generating utils/ipc/mojom_templates with a custom command
FAILED: utils/ipc/libcamera_templates.zip
/home/luis/libcamera/utils/ipc/./generate.py -o utils/ipc precompile
Traceback (most recent call last):
  File "/home/luis/libcamera/utils/ipc/./generate.py", line 15, in <module>
    import mojo.public.tools.bindings.mojom_bindings_generator as generator
  File "/home/luis/libcamera/utils/ipc/mojo/public/tools/bindings/mojom_bindings_generator.py", line 43, in <module>
    from mojom.generate import template_expander
  File "/home/luis/libcamera/utils/ipc/mojo/public/tools/mojom/mojom/generate/template_expander.py", line 13, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
ninja: build stopped: subcommand failed.
luis@Ubuntu-RPi4:~/libcamera$
```

**Comment by eli-schwartz** [comment]
Run `ninja -C build/` to compile the project ***without*** performing compilation as sudo.

Afterwards, you may install with sudo.

**Comment by lm782** [comment]
Permission denied without sudo. 
```
luis@Ubuntu-RPi4:~/libcamera$ ninja -C build/
ninja: Entering directory `build/'
[1/164] Generating include/libcamera/internal/tp_header with a custom command
ninja: build stopped: Error writing to build log: Permission denied.
luis@Ubuntu-RPi4:~/libcamera$ 
```

**Comment by lm782** [comment]
I gave up on that build and started anew on an RPi CM4 and CM4io. Still Ubuntu 22.04 LTS, but this time I made sure the path was right for Meson. 
Got an error running "ninja -C build install"
```
[203/204] Installing files.
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
Traceback (most recent call last):
  File "/home/luis/.local/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
FAILED: meson-internal__install 
/home/luis/.local/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```
Thought I check in before running it again, but this time as sudo. 
Any insight?

**Comment by eli-schwartz** [comment]
> File "/home/luis/.local/bin/meson", line 5, in <module>

You're using a `--user` installed version of Meson, here.

**Comment by lm782** [comment]
Thanks for the help. I scrapped the CM4 build. Could not get the camera recognized using RPi OS and libcamera-hello. Going back to the RPi4 (where the camera was recognized when configure with RPi OS and libcamera-hello). 

Have read enough posts now to understand what I'm dealing with is a configuration problem between 'user' vs 'root' meson installations, which (in my layman's interpretation) hinders or confuses interactions with ninja. 

I'm starting over with a new Ubuntu 22.04 LTS image on the SD card. After apt update, upgrade and reboot, "apt list --installed" shows nothing starting with "meson" or "ninja".  

Will start the libcamera build by installing the required, recommended and various optional dependencies. 

To avoid any further issues between ninja, meson (other libraries?), user and root - what should I do (or avoid doing) in this build (my fourth…)?

**Comment by eli-schwartz** [comment]
Just install Meson (and ninja) from apt, and forget that pip exists.

Pip is okay if you do NOT intend to install software as root, but you do intend to install software as root, so apt-get it is.

**Comment by lm782** [comment]
Done. Thank you ever so kindly for the help and patience. I'm now on to the next level of troubleshooting. 

libcamera recognized the camera (imx477), but it failed to register and is not available. 
ERROR RPI dma_heaps.cpp:53 Could not open any dmaHeap device
and
ERROR RPI raspberrypi.cpp:1278 Failed to register camera imx477 10-001a: -12

**Comment by lm782** [comment]
Added me to the video group and neither of those errors come up. 

"cam -l" does not list a camera, and "cam -c 1 --capture=10 --file" returns "Camera 1 not found. Failed to create camera session." 

Time to close this issue and start one specific to the current one?

**Comment by eli-schwartz** [comment]
No problem, happy to help. :)

And yes, this does seem like an entirely different problem -- the meson compilation issues (which are my personal area of expertise) are solved.

**Comment by lm782** [comment]
Thanks again for the help.
