### ISSUE TITLE
Libcamera Patchwork

### ISSUE THREAD

**Issue by thisuser14343** [libcamera-org/libcamera#7]
Hello. I was wondering if any of the patchwork for libcamera which is done at https://patchwork.libcamera.org is going to be merged into libcamera for the upcoming v0.0.6?

**Comment by kbingham** [comment]
Can you be more specific? Which patches are you looking for? Patches get merged when they are successfully reviewed and tested.

**Comment by kbingham** [comment]
If there are patches you'd like to help get merged - code review on the patches on the mailing list is always appreciated. That's what blocks merging most of the time.

**Comment by kbingham** [comment]
No - I don't believe it has yet. It's being developed by [Daniel Semkowicz](https://patchwork.libcamera.org/project/libcamera/list/?submitter=126): 

 and the latest version appears to be https://patchwork.libcamera.org/project/libcamera/list/?series=3831

I can't guarantee that a given set of patches will be in a specific version as we aim for time based releases not feature based releases. Whatever features are ready and merged at the time of release will be the ones included.

If you need specific features, you can support that development by either reviewing code, testing the patches, or supporting the developer who is working on it directly, or by taking the patches and assisting with the development itself.
