### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [libcamera-org/libcamera#9]
Is it possible next time on release new version make the github release to have entry on https://github.com/libcamera-org/libcamera/releases which is now empty? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by kbingham** [comment]
This is just a convenience mirror. The official repository is https://git.libcamera.org/libcamera/libcamera.git


Releases are notified on the libcamera mailing list.

**Comment by kbingham** [comment]
If there's an automatic way to make GitHub know tags are releases then sure but if it's a manual process then it won't be something that will be handled.

**Comment by kbingham** [comment]
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release looks like it might be possible. But this isn't high on my priorities

**Comment by kbingham** [comment]
Closing. Releases are available at https://gitlab.freedesktop.org/camera/libcamera/-/releases
